### PR TITLE
Extends `react-click-outside` to also work with other events like mousedown

### PR DESCRIPTION
**Pull request by CaptEmulation**
We had a desire to be able to dismiss components on a mousedown rather than a click event.  This PR lets users choose to listen for other "mouse like" events targeting outside the component.  Full backwards compatibility is retained with existing code.

In addition as part of doing a private scoped release I took it upon myself to remove the `dist/index.js` file from the repo and added a `prepublishOnly` npm script which will automatically build this file when publishing so that it is not necessary to commit to repo.  Let me know if you'd like me to revert this portion of the PR as I know it is a side issue.

### CODE REVIEW

**Comment by kentor** [comment]
curious why you needed this?

**Comment by CaptEmulation** [comment]
> curious why you needed this?

We wanted the library to work exactly like it did but to trigger on `mousedown` instead of `click` so that we could dismiss when user presses mouse button instead of when they release mouse button.

**Comment by kentor** [comment]
yes i know that is what you want, but why do you want to allow dismissal on mouse press instead of release?

**Comment by CaptEmulation** [comment]
It's a very uninteresting tale.  Some people went into a room and came out with a bunch of development tickets and I picked up this one.  I honestly don't have any strong feelings on the why or why not.   I published this as `@captemulation/react-click-outside` and we are using that.  I try to contribute back to OSS when I can but my feelings won't be hurt if you don't want these changes.  ☮️

**Comment by kentor** [comment]
I see. Interesting nonetheless. Well until there is more need for this I will close this for now.

**Pull request closed without merging**
