### PR TITLE
add mouseup event to trigger handleClickOutside

### PR DESCRIPTION
**Pull request by thewillhuang**
On chrome, there are times when you are doing a drag motion for handleClickOutside to not trigger, especially over another component that swallows events. This addition adds the `mouseup` event to account for dragging motion.

### CODE REVIEW

**Comment by kentor** [comment]
Not really understanding the issue.
1) Won't this change trigger handleClickOutside twice?
2) What do you mean over another component that swallows events?

**Comment by thewillhuang** [comment]
well the specific problem i am having is with https://github.com/kirjs/react-highcharts being broken in chrome occasionally. sometimes the handleClickOutside triggers when you do a click-drag action over a rendered highcharts component, other times, it would not trigger. I think potentially a better fix would be to trigger it on mouseup because it would account for dragging like behavior.

**Comment by kentor** [comment]
Hmm.. I would need to see a repro of this. I can test it out when I have time or if you can create a demo of this.

**Comment by kentor** [comment]
closing this. let me know if you still want this fixed and can provide a repo

**Pull request closed without merging**
